# Generated by Django 3.0.14 on 2021-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('대중교통 이용', '대중교통 이용'), ('친환경 제품 사용', '친환경 제품 사용'), ('분리수거', '분리수거'), ('비거니즘 실천', '비거니즘 실천'), ('etc', 'etc')], max_length=50),
        ),
    ]
