# Generated by Django 3.1.5 on 2021-05-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210519_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='api.area'),
        ),
    ]
