# Generated by Django 3.1.5 on 2021-05-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pollution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pollution',
        ),
    ]
